name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Clear
      run: cargo clean
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: |
        cargo build
        Copy-Item .\resources\ .\target\debug\
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: game
        path: |
          target/debug/game.exe
          resources
    
