name: Rust build

on: workflow_dispatch 

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Clear
      run: cargo clean
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: |
        cargo build
        Copy-Item .\target\debug\game.exe .\
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: game
        path: |
          resources
          game.exe
          
    
