name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Clear
      run: cargo clean
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose
